# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/Desktop/ft_regex

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/Desktop/ft_regex

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Desktop/ft_regex/CMakeFiles /root/Desktop/ft_regex/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Desktop/ft_regex/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ft_regex

# Build rule for target.
ft_regex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ft_regex
.PHONY : ft_regex

# fast build rule for target.
ft_regex/fast:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/build
.PHONY : ft_regex/fast

src/ft_regex.o: src/ft_regex.c.o

.PHONY : src/ft_regex.o

# target to build an object file
src/ft_regex.c.o:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/ft_regex.c.o
.PHONY : src/ft_regex.c.o

src/ft_regex.i: src/ft_regex.c.i

.PHONY : src/ft_regex.i

# target to preprocess a source file
src/ft_regex.c.i:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/ft_regex.c.i
.PHONY : src/ft_regex.c.i

src/ft_regex.s: src/ft_regex.c.s

.PHONY : src/ft_regex.s

# target to generate assembly for a file
src/ft_regex.c.s:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/ft_regex.c.s
.PHONY : src/ft_regex.c.s

src/ft_regex_debug.o: src/ft_regex_debug.c.o

.PHONY : src/ft_regex_debug.o

# target to build an object file
src/ft_regex_debug.c.o:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/ft_regex_debug.c.o
.PHONY : src/ft_regex_debug.c.o

src/ft_regex_debug.i: src/ft_regex_debug.c.i

.PHONY : src/ft_regex_debug.i

# target to preprocess a source file
src/ft_regex_debug.c.i:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/ft_regex_debug.c.i
.PHONY : src/ft_regex_debug.c.i

src/ft_regex_debug.s: src/ft_regex_debug.c.s

.PHONY : src/ft_regex_debug.s

# target to generate assembly for a file
src/ft_regex_debug.c.s:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/ft_regex_debug.c.s
.PHONY : src/ft_regex_debug.c.s

src/ft_regex_free.o: src/ft_regex_free.c.o

.PHONY : src/ft_regex_free.o

# target to build an object file
src/ft_regex_free.c.o:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/ft_regex_free.c.o
.PHONY : src/ft_regex_free.c.o

src/ft_regex_free.i: src/ft_regex_free.c.i

.PHONY : src/ft_regex_free.i

# target to preprocess a source file
src/ft_regex_free.c.i:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/ft_regex_free.c.i
.PHONY : src/ft_regex_free.c.i

src/ft_regex_free.s: src/ft_regex_free.c.s

.PHONY : src/ft_regex_free.s

# target to generate assembly for a file
src/ft_regex_free.c.s:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/ft_regex_free.c.s
.PHONY : src/ft_regex_free.c.s

src/group.o: src/group.c.o

.PHONY : src/group.o

# target to build an object file
src/group.c.o:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/group.c.o
.PHONY : src/group.c.o

src/group.i: src/group.c.i

.PHONY : src/group.i

# target to preprocess a source file
src/group.c.i:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/group.c.i
.PHONY : src/group.c.i

src/group.s: src/group.c.s

.PHONY : src/group.s

# target to generate assembly for a file
src/group.c.s:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/group.c.s
.PHONY : src/group.c.s

src/new_code.o: src/new_code.c.o

.PHONY : src/new_code.o

# target to build an object file
src/new_code.c.o:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/new_code.c.o
.PHONY : src/new_code.c.o

src/new_code.i: src/new_code.c.i

.PHONY : src/new_code.i

# target to preprocess a source file
src/new_code.c.i:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/new_code.c.i
.PHONY : src/new_code.c.i

src/new_code.s: src/new_code.c.s

.PHONY : src/new_code.s

# target to generate assembly for a file
src/new_code.c.s:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/new_code.c.s
.PHONY : src/new_code.c.s

src/quantifier.o: src/quantifier.c.o

.PHONY : src/quantifier.o

# target to build an object file
src/quantifier.c.o:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/quantifier.c.o
.PHONY : src/quantifier.c.o

src/quantifier.i: src/quantifier.c.i

.PHONY : src/quantifier.i

# target to preprocess a source file
src/quantifier.c.i:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/quantifier.c.i
.PHONY : src/quantifier.c.i

src/quantifier.s: src/quantifier.c.s

.PHONY : src/quantifier.s

# target to generate assembly for a file
src/quantifier.c.s:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/quantifier.c.s
.PHONY : src/quantifier.c.s

src/set.o: src/set.c.o

.PHONY : src/set.o

# target to build an object file
src/set.c.o:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/set.c.o
.PHONY : src/set.c.o

src/set.i: src/set.c.i

.PHONY : src/set.i

# target to preprocess a source file
src/set.c.i:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/set.c.i
.PHONY : src/set.c.i

src/set.s: src/set.c.s

.PHONY : src/set.s

# target to generate assembly for a file
src/set.c.s:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/set.c.s
.PHONY : src/set.c.s

src/string.o: src/string.c.o

.PHONY : src/string.o

# target to build an object file
src/string.c.o:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/string.c.o
.PHONY : src/string.c.o

src/string.i: src/string.c.i

.PHONY : src/string.i

# target to preprocess a source file
src/string.c.i:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/string.c.i
.PHONY : src/string.c.i

src/string.s: src/string.c.s

.PHONY : src/string.s

# target to generate assembly for a file
src/string.c.s:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/string.c.s
.PHONY : src/string.c.s

src/unescape.o: src/unescape.c.o

.PHONY : src/unescape.o

# target to build an object file
src/unescape.c.o:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/unescape.c.o
.PHONY : src/unescape.c.o

src/unescape.i: src/unescape.c.i

.PHONY : src/unescape.i

# target to preprocess a source file
src/unescape.c.i:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/unescape.c.i
.PHONY : src/unescape.c.i

src/unescape.s: src/unescape.c.s

.PHONY : src/unescape.s

# target to generate assembly for a file
src/unescape.c.s:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/unescape.c.s
.PHONY : src/unescape.c.s

src/valid_param.o: src/valid_param.c.o

.PHONY : src/valid_param.o

# target to build an object file
src/valid_param.c.o:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/valid_param.c.o
.PHONY : src/valid_param.c.o

src/valid_param.i: src/valid_param.c.i

.PHONY : src/valid_param.i

# target to preprocess a source file
src/valid_param.c.i:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/valid_param.c.i
.PHONY : src/valid_param.c.i

src/valid_param.s: src/valid_param.c.s

.PHONY : src/valid_param.s

# target to generate assembly for a file
src/valid_param.c.s:
	$(MAKE) -f CMakeFiles/ft_regex.dir/build.make CMakeFiles/ft_regex.dir/src/valid_param.c.s
.PHONY : src/valid_param.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ft_regex"
	@echo "... src/ft_regex.o"
	@echo "... src/ft_regex.i"
	@echo "... src/ft_regex.s"
	@echo "... src/ft_regex_debug.o"
	@echo "... src/ft_regex_debug.i"
	@echo "... src/ft_regex_debug.s"
	@echo "... src/ft_regex_free.o"
	@echo "... src/ft_regex_free.i"
	@echo "... src/ft_regex_free.s"
	@echo "... src/group.o"
	@echo "... src/group.i"
	@echo "... src/group.s"
	@echo "... src/new_code.o"
	@echo "... src/new_code.i"
	@echo "... src/new_code.s"
	@echo "... src/quantifier.o"
	@echo "... src/quantifier.i"
	@echo "... src/quantifier.s"
	@echo "... src/set.o"
	@echo "... src/set.i"
	@echo "... src/set.s"
	@echo "... src/string.o"
	@echo "... src/string.i"
	@echo "... src/string.s"
	@echo "... src/unescape.o"
	@echo "... src/unescape.i"
	@echo "... src/unescape.s"
	@echo "... src/valid_param.o"
	@echo "... src/valid_param.i"
	@echo "... src/valid_param.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

